### PR TITLE
Travis setup

### PR DESCRIPTION
**Pull request by renemilk**
I'm doing this from a fork because (afaict) being a contributor does not allow me to activate travis for this repo. In light of potential further integrations (at least coveralls.io) would you mind moving this repo to an organization?

### CODE REVIEW

**Comment by somada141** [comment]
righto that should do it

**Comment by renemilk** [comment]
Almost, you should have gotten two auth requests for the org for travis and coverall now.

**Comment by somada141** [comment]
yep, just approved them

**Comment by renemilk** [comment]
It seems I've never tried to enable Travis for a repo where I don't have admin rights, because I just found out that you need admin rights to enable :wink: 
https://travis-ci.org/profile/pyscience-projects

Coveralls was fine w/o them though.

**Comment by somada141** [comment]
just enabled it on Travis, never used organizations before as I typically work w Gitlab

**Pull request merged**
